# Generated by Django 4.2.20 on 2025-04-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=16)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('2', 'Accepted'), ('1', 'Pending')], max_length=3)),
                ('id_friend_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend', to='Users.user')),
                ('id_friend_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend', to='Users.user')),
            ],
        ),
    ]
