# Generated by Django 4.2.20 on 2025-05-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Accepted')], max_length=3),
        ),
    ]
