# Generated by Django 5.2 on 2025-05-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_friends_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Accepted')], max_length=3),
        ),
    ]
