# Generated by Django 4.2.20 on 2025-05-01 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages_to_group',
            name='sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='messages_to_user',
            name='sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
