# Generated by Django 5.2 on 2025-05-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_messages_to_group_sent_messages_to_user_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages_to_group',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
